sudo: required
services:
 - docker

before_install:
 - docker build -t henrykizdebski/docker-react -f Dockerfile.dev .

script:
  - docker run henrykizdebski/docker-react npm run test -- --coverage

deploy:
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2" 
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-446518935327"
  bucket_path: "docker"  
   on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_key_key: 
   secure: "$AWS_SECRET_KEY"
